spring:
  application:
    name: order-service
  cloud:
    config:
      override-none: true
server:
  port: 8201

eureka:
  client:
    service-url:
      #如果有公共的云服务直接在这里写就可以
      #要是私有服务器就要添加defaultZone这个属性，写自己私有的地址
      defaultZone: http://127.0.0.1:2001/eureka,http://127.0.0.1:2002/eureka

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream